services:
  - type: web
    name: salas-conectadas-cepi
    env: node
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Cria dependência para garantir que o banco de dados seja criado primeiro
    autoDeploy: true
    # Configuração para determinar quando o serviço está pronto
    disk:
      name: salasconectadas
      mountPath: /data
      sizeGB: 1
    plan: free
    # Conecta explicitamente ao banco de dados
    database:
      name: salas_conectadas_postgres
      ipAllowList: [] # Permite todas as conexões

# Configuração do banco de dados
databases:
  - name: salas_conectadas_postgres
    databaseName: salas_conectadas_cepi
    plan: free
    user: salas_admin
    ipAllowList: [] # Permite todas as conexões